# Generated by Django 5.0.2 on 2024-06-12 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0014_alter_ticket_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashfree_id', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('payment_request_id', models.CharField(max_length=100)),
                ('payment_amount', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='products.order')),
            ],
        ),
    ]
