# Generated by Django 5.0.2 on 2024-07-02 02:26

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('name', models.CharField(max_length=30)),
                ('mini_content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('web_image', models.ImageField(upload_to='')),
                ('mobile_image', models.ImageField(upload_to='')),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
