# Generated by Django 5.0.2 on 2024-07-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_keywords',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
