# Generated by Django 5.0.2 on 2024-05-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_user_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
        migrations.AddField(
            model_name='user',
            name='pan_card',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
