# Generated by Django 5.0.2 on 2024-05-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_user_group_remove_user_rating_user_pan_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pan_card',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
