# Generated by Django 5.0.2 on 2024-07-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_user_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[(0, 'New Delhi'), (1, 'Gurgaon'), (2, 'Noida'), (3, 'Kolkata'), (4, 'Mumbai'), (5, 'Chandigarh'), (6, 'Hyderabad'), (7, 'Vadodara'), (8, 'Lucknow'), (9, 'Bangalore'), (10, 'Kochi'), (11, 'Chennai'), (12, 'Ludhiana'), (13, 'Jalandhar'), (14, 'Amritsar'), (15, 'Ahmedabad'), (16, 'Trichy'), (17, 'Pune'), (18, 'Calicut'), (-1, 'All')], max_length=40, null=True),
        ),
    ]
