# Generated by Django 5.0.2 on 2024-07-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_user_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('New Delhi', 'New Delhi'), ('Gurgaon', 'Gurgaon'), ('Noida', 'Noida'), ('Kolkata', 'Kolkata'), ('Mumbai', 'Mumbai'), ('Chandigarh', 'Chandigarh'), ('Hyderabad', 'Hyderabad'), ('Vadodara', 'Vadodara'), ('Lucknow', 'Lucknow'), ('Bangalore', 'Bangalore'), ('Kochi', 'Kochi'), ('Chennai', 'Chennai'), ('Ludhiana', 'Ludhiana'), ('Jalandhar', 'Jalandhar'), ('Amritsar', 'Amritsar'), ('Ahmedabad', 'Ahmedabad'), ('Trichy', 'Trichy'), ('Pune', 'Pune'), ('Calicut', 'Calicut'), ('all', 'all')], max_length=40, null=True),
        ),
    ]
