# Generated by Django 5.0.2 on 2024-05-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forex',
            name='currency',
            field=models.CharField(default='USD', max_length=4),
        ),
    ]
