# Generated by Django 5.0.2 on 2024-05-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_forex_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='file_back',
            field=models.FileField(blank=True, null=True, upload_to='passport/back/'),
        ),
        migrations.AddField(
            model_name='passport',
            name='file_front',
            field=models.FileField(blank=True, null=True, upload_to='passport/front/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ticket/'),
        ),
        migrations.AddField(
            model_name='visa',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='visa/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', max_length=4),
        ),
    ]
