# Generated by Django 5.0.2 on 2024-05-23 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_extradocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='pan/')),
                ('type', models.CharField(default='User', max_length=40)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pan', to='products.order')),
            ],
            options={
                'verbose_name': 'Pan',
                'verbose_name_plural': 'Pan',
            },
        ),
    ]
