# Generated by Django 5.0.2 on 2024-06-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_resume_userquery_company_userquery_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='outlets/')),
                ('name', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=40)),
                ('phone_no', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('timming_weekdays', models.CharField(max_length=40)),
                ('timming_weekend', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
