# Generated by Django 5.0.2 on 2024-06-03 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_order_product_order_gst_amount_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='forex_rate',
        ),
    ]
