# Generated by Django 5.0.2 on 2024-06-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_order_forex_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='bs',
            field=models.CharField(default='Buy', max_length=4),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='currency',
            field=models.CharField(default='USD', max_length=4),
        ),
    ]
