# Generated by Django 5.0.2 on 2024-06-08 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_orderitems_bs_orderitems_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelievryAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('phone_no', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delievry_adress', to='products.order')),
            ],
            options={
                'verbose_name': 'DelievryAdress',
                'verbose_name_plural': 'DelievryAdress',
            },
        ),
    ]
