# Generated by Django 5.0.2 on 2024-06-10 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_delievryadress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
