# Generated by Django 5.0.2 on 2024-06-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_ticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='delievryadress',
            name='landmark',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='delievryadress',
            name='pincode',
            field=models.CharField(default='', max_length=6),
        ),
    ]
