# Generated by Django 5.0.2 on 2024-07-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_delievryadress_country_code_alter_order_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, choices=[('New Delhi', 'New Delhi'), ('Gurgaon', 'Gurgaon'), ('Noida', 'Noida'), ('Kolkata', 'Kolkata'), ('Mumbai', 'Mumbai'), ('Chandigarh', 'Chandigarh'), ('Hyderabad', 'Hyderabad'), ('Vadodara', 'Vadodara'), ('Lucknow', 'Lucknow'), ('Bangalore', 'Bangalore'), ('Kochi', 'Kochi'), ('Chennai', 'Chennai'), ('Ludhiana', 'Ludhiana'), ('Jalandhar', 'Jalandhar'), ('Amritsar', 'Amritsar'), ('Ahmedabad', 'Ahmedabad'), ('Trichy', 'Trichy'), ('Pune', 'Pune'), ('Calicut', 'Calicut'), ('all', 'All')], max_length=40, null=True),
        ),
    ]
