# Generated by Django 5.0.2 on 2024-07-08 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='forex',
            name='markdownPercentage',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='forex',
            name='markupPercentage',
            field=models.FloatField(default=0.1),
        ),
        migrations.CreateModel(
            name='TravelerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(default='91', max_length=5)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=40)),
                ('panNumber', models.CharField(max_length=12)),
                ('phone_no', models.CharField(max_length=14)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traveler_details', to='products.order')),
            ],
        ),
    ]
