# Generated by Django 5.0.2 on 2024-07-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_forex_markdownpercentage_forex_markuppercentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('New Delhi', 'New Delhi'), ('Gurgaon', 'Gurgaon'), ('Noida', 'Noida'), ('Kolkata', 'Kolkata'), ('Mumbai', 'Mumbai'), ('Chandigarh', 'Chandigarh'), ('Hyderabad', 'Hyderabad'), ('Vadodara', 'Vadodara'), ('Lucknow', 'Lucknow'), ('Bangalore', 'Bangalore'), ('Kochi', 'Kochi'), ('Chennai', 'Chennai'), ('Ludhiana', 'Ludhiana'), ('Jalandhar', 'Jalandhar'), ('Amritsar', 'Amritsar'), ('Ahmedabad', 'Ahmedabad'), ('Trichy', 'Trichy'), ('Pune', 'Pune'), ('Calicut', 'Calicut'), ('all', 'All')], max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('markup_percentage', models.FloatField(default=0.1)),
                ('markdown_percentage', models.FloatField(default=0.1)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'City',
            },
        ),
    ]
