# Generated by Django 5.0.2 on 2024-07-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='forex',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(choices=[('New Delhi', 'New Delhi'), ('Gurgaon', 'Gurgaon'), ('Noida', 'Noida'), ('Kolkata', 'Kolkata'), ('Mumbai', 'Mumbai'), ('Chandigarh', 'Chandigarh'), ('Hyderabad', 'Hyderabad'), ('Vadodara', 'Vadodara'), ('Lucknow', 'Lucknow'), ('Bangalore', 'Bangalore'), ('Kochi', 'Kochi'), ('Chennai', 'Chennai'), ('Ludhiana', 'Ludhiana'), ('Jalandhar', 'Jalandhar'), ('Amritsar', 'Amritsar'), ('Ahmedabad', 'Ahmedabad'), ('Trichy', 'Trichy'), ('Pune', 'Pune'), ('Calicut', 'Calicut'), ('all', 'all')], max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, choices=[('New Delhi', 'New Delhi'), ('Gurgaon', 'Gurgaon'), ('Noida', 'Noida'), ('Kolkata', 'Kolkata'), ('Mumbai', 'Mumbai'), ('Chandigarh', 'Chandigarh'), ('Hyderabad', 'Hyderabad'), ('Vadodara', 'Vadodara'), ('Lucknow', 'Lucknow'), ('Bangalore', 'Bangalore'), ('Kochi', 'Kochi'), ('Chennai', 'Chennai'), ('Ludhiana', 'Ludhiana'), ('Jalandhar', 'Jalandhar'), ('Amritsar', 'Amritsar'), ('Ahmedabad', 'Ahmedabad'), ('Trichy', 'Trichy'), ('Pune', 'Pune'), ('Calicut', 'Calicut'), ('all', 'all')], max_length=40, null=True),
        ),
    ]
