# Generated by Django 5.0.2 on 2024-07-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_forex_priority_alter_city_name_alter_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='forex',
            name='can_buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forex',
            name='cardMarkdownPercentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='forex',
            name='cardMarkupPercentage',
            field=models.FloatField(default=0),
        ),
    ]
