# Generated by Django 5.0.2 on 2024-07-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_forex_can_buy_forex_cardmarkdownpercentage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outlets',
            options={'verbose_name': 'Outlets', 'verbose_name_plural': 'Outlets'},
        ),
    ]
