# Generated by Django 5.0.2 on 2024-08-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_outlets_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='forex',
            name='can_transfer',
            field=models.BooleanField(default=False),
        ),
    ]
