# Generated by Django 5.0.2 on 2024-08-03 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_forex_can_transfer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='purous_of_visit',
            new_name='purpose_of_visit',
        ),
    ]
