# Generated by Django 5.0.2 on 2024-08-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_rename_purous_of_visit_order_purpose_of_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
    ]
