# Generated by Django 5.0.2 on 2024-11-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_order_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelerdetails',
            name='panNumber',
            field=models.CharField(blank=True, default='', max_length=12, null=True),
        ),
    ]
